package com.tkx.driver;

public class BookingDetail {
    public int id;
    public int booking_id;
    public String collection_vicinity;
    public String delivery_vicinity;
    public String delivery_receiver_name;
    public String delivery_receipt_image;
    public String receipt_latitude;
    public String receipt_longitude;
    public String receipt_date;
    public String start_meter_image;
    public String start_meter_value;
    public String end_meter_value;
    public String end_meter_image;
    public String accept_timestamp;
    public String accept_latitude;
    public String accept_longitude;
    public String accuracy_at_accept;
    public String arrive_timestamp;
    public String arrive_latitude;
    public String arrive_longitude;
    public String accuracy_at_arrive;
    public String start_timestamp;
    public String start_latitude;
    public String start_longitude;
    public String start_location;
    public String accuracy_at_start;
    public String dead_milage_distance;
    public String end_timestamp;
    public String end_latitude;
    public String end_longitude;
    public String end_location;
    public String accuracy_at_end;
    public String wait_time;
    public String bill_details;
    public String total_amount;
    public String promo_discount;
    public String wallet_deduct_money;
    public String pending_amount;
    public String tip_amount;
    public String payment_failure;
    public String created_at;
    public String updated_at;
}
