package com.tkx.driver;

public class Data {
    public int id;
    public int merchant_id;
    public int vehicle_type_id;
    public int country_area_id;
    public int price_card_id;
    public String ride_otp;
    public int ride_otp_verify;
    public int total_drop_location;
    public int service_type_id;
    public String ploy_points;
    public int driver_id;
    public int booking_status;
    public String pickup_latitude;
    public String pickup_longitude;
    public String drop_latitude;
    public String drop_longitude;
    public String additional_notes;
    public int family_member_id;
    public int onride_waiting_type;
    public String delivery_type_id;
    public boolean send_meter_image;
    public boolean send_meter_value;
    public boolean sos_visibility;
    public String[] sos;
    public boolean onride_pause_button;
    public PolyData polydata;
    public StillMarker still_marker;
    public MovableMarker movable_marker;
    public Location location;
    public boolean cancelable;
    public FamilyMemberDetails family_member_details;
    public PaymentMethod payment_method;
    public VehicleType vehicle_type;
    public User user;
    public BookingDetail booking_detail;
    public boolean manual_toll_enable;
}
